require "huella_ambiental/version"
require "huella_ambiental/Alimento.rb"
require "huella_ambiental/Dieta.rb"
require "huella_ambiental/Lista.rb"
require "huella_ambiental/Nodo.rb"
require "huella_ambiental/Plato.rb"
require "huella_ambiental/PlatoExtendido.rb"
require "huella_ambiental/Menu.rb"
